### ISSUE TITLE
Uncaught TypeError: Cannot read property 'clear' of null

### ISSUE THREAD

**Issue by watro** [queenp/punchclock#11]
I just opened Atom and got this exception at start, did not do anything else.

1. Open Atom

**Atom Version**: 1.0.19
**System**: Mac OS X 10.10.5
**Thrown From**: [punchclock](https://github.com/queenp/punchclock) package, v0.6.3

### Stack Trace

Uncaught TypeError: Cannot read property 'clear' of null

```
At /Users/watro/.atom/packages/punchclock/lib/timer.coffee:537

TypeError: Cannot read property 'clear' of null
    at Timer.module.exports.Timer.clearStatus (/Users/watro/.atom/packages/punchclock/lib/timer.coffee:537:28)
    at Timer.module.exports.Timer.didChangePaths (/Users/watro/.atom/packages/punchclock/lib/timer.coffee:213:18)
    at /Users/watro/.atom/packages/punchclock/lib/punchclock.coffee:83:24
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:82:11)
    at Project.module.exports.Project.addPath (/Applications/Atom.app/Contents/Resources/app.asar/src/project.js:279:29)
    at EventEmitter.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:37:32)
    at emitTwo (events.js:87:13)
    at EventEmitter.emit (events.js:172:7)
    at EventEmitter.ipc.sendSync (/Applications/Atom.app/Contents/Resources/atom.asar/renderer/api/lib/ipc.js:21:31)
    at BrowserWindow.RemoteMemberFunction [as isMaximized] (/Applications/Atom.app/Contents/Resources/atom.asar/renderer/api/lib/remote.js:140:29)
    at Atom.module.exports.Atom.getWindowDimensions (/Applications/Atom.app/Contents/Resources/app.asar/src/atom.js:557:33)
    at Atom.module.exports.Atom.storeDefaultWindowDimensions (/Applications/Atom.app/Contents/Resources/app.asar/src/atom.js:588:25)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:104:21
    at handler (/Applications/Atom.app/Contents/Resources/app.asar/src/space-pen-extensions.js:115:32)
    at jQuery.event.dispatch (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/space-pen/vendor/jquery.js:4681:9)
    at elemData.handle (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/space-pen/vendor/jquery.js:4359:46)
```

### Commands

```
```

### Config

```json
{
  "core": {
    "projectHome": "/Users/watro/Documents/dev"
  }
}
```

### Installed Packages

```coffee
# User
MavensMate-Atom, v1.0.6
atom-alignment, v0.12.1
autoclose-html, v0.19.0
color-picker, v2.0.13
file-icons, v1.6.10
highlight-line, v0.11.0
highlight-selected, v0.10.1
linter, v1.8.1
linter-jshint, v1.2.1
local-history, v3.2.3
minimap, v4.13.4
minimap-highlight-selected, v4.3.1
open-recent, v2.3.0
pigments, v0.17.1
project-manager, v2.6.4
punchclock, v0.6.3

# Dev
No dev packages
```

**Comment by queenp** [comment]
Hi, I'm having a bit of a difficulty replicating this error. Investing a bit of time in updating punchclock this weekend, will see if I can figure out what's up.

**Comment by queenp** [comment]
Could you confirm whether it's still happening?
