### ISSUE TITLE
Uncaught TypeError: startDateObject.twix is not a function

### ISSUE THREAD

**Issue by AshleyWright** [queenp/punchclock#12]
1. start time tracking
2. finish time tracking.

**Atom Version**: 1.0.19
**System**: Mac OS X 10.10.5
**Thrown From**: [punchclock](https://github.com/queenp/punchclock) package, v0.6.3

### Stack Trace

Uncaught TypeError: startDateObject.twix is not a function

```
At /Users/ashleywright/.atom/packages/punchclock/lib/timer.coffee:407

TypeError: startDateObject.twix is not a function
  at Timer.module.exports.Timer.getPath (/Users/ashleywright/.atom/packages/punchclock/lib/timer.coffee:407:41)
  at Timer.module.exports.Timer.save (/Users/ashleywright/.atom/packages/punchclock/lib/timer.coffee:338:30)
  at Timer.module.exports.Timer.finish (/Users/ashleywright/.atom/packages/punchclock/lib/timer.coffee:187:14)
  at atom-workspace.<anonymous> (/Users/ashleywright/.atom/packages/punchclock/lib/punchclock.coffee:55:76)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:245:29)
  at /Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61
  at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:524:16)
  at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:347:22)
  at HTMLDocument.module.exports.WindowEventHandler.onKeydown (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:184:20)

```

### Commands

```
     -0:10.2.0 punchclock:finish (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "wrap-guide",
      "background-tips",
      "synesthesia",
      "font-viewer",
      "quick-editor",
      "svg-preview",
      "slack-chat",
      "symbols-view"
    ],
    "packagesWithKeymapsDisabled": [
      "bottom-dock",
      "punchclock",
      "tree-view",
      "term2",
      "symbols-tree-view",
      "tree-view-git-status",
      "git-blame",
      "git-control",
      "status-bar",
      "sublime-panes",
      "project-ring",
      "tree-ignore"
    ],
    "themes": [
      "one-dark-ui",
      "cobalt2-syntax"
    ],
    "destroyEmptyPanes": false
  }
}
```

### Installed Packages

```coffee
# User
Rdio, v0.6.0
Stylus, v1.2.1
Sublime-Style-Column-Selection, v1.3.0
aligner, v0.17.0
aligner-php, v1.0.0
aligner-scss, v1.1.0
antialiased, v0.1.0
atom-ctags, v4.3.0
atom-image-resize, v0.3.0
atom-punchtime, v0.0.0
autocomplete-modules, v1.3.0
autocomplete-php, v0.3.7
blackspace, v1.1.0
bottom-dock, v0.3.5
change-case, v0.6.0
clipboard-history, v0.6.6
cobalt2-syntax, v0.2.1
coffee-navigator, v0.0.16
color-picker, v2.0.13
css-comb, v2.4.0
docblockr, v0.7.3
editorconfig, v1.2.0
emmet, v2.3.13
emmet-snippets-compatibility, v1.0.0
file-icons, v1.6.11
git-hide, v0.1.2
git-log, v0.4.1
grunt-manager, v0.1.10
gulp-manager, v0.2.12
gutter-shadow, v0.5.0
hex, v0.6.2
highlight-line, v0.11.0
highlight-selected, v0.10.1
http-status-codes, v1.0.4
imdone-atom, v1.1.47
jshint, v1.8.1
language-SCSS, v0.4.0
language-dots, v0.0.4
language-log, v1.0.0
language-lua, v0.9.4
language-pfm, v0.82.0
language-plantuml, v0.1.1
language-sql-mysql, v0.3.1
linter, v1.8.1
linter-coffeescript, v1.0.0
linter-jshint, v1.2.1
linter-less, v2.2.0
linter-manager, v0.2.3
linter-php, v1.0.5
linter-scss-lint, v2.3.0
linter-stylint, v2.0.1
linter-xmllint, v0.0.7
markdown-preview-opener, v0.1.1
minimap, v4.13.4
minimap-autohide, v0.10.1
minimap-codeglance, v0.4.2
minimap-find-and-replace, v4.3.1
minimap-git-diff, v4.1.8
minimap-highlight-selected, v4.3.1
minimap-linter, v1.0.0
minimap-pigments, v0.1.7
minimap-selection, v4.3.1
multi-wrap-guide, v0.22.3
pdf-view, v0.34.0
pigments, v0.18.0
preview-inline, v0.5.1
project-colorize, v0.2.0
project-ring, v0.35.2
punchclock, v0.6.3
quick-docs, v0.1.0
simple-drag-drop-text, v0.3.0
space-tab, v0.4.2
status-bar-clock, v2.0.4
symbols-tree-view, v0.10.1
tag, v0.3.0
todo-manager, v0.2.5
tree-ignore, v0.2.6
tree-view-git-status, v0.2.2

# Dev
No dev packages
```

**Comment by queenp** [comment]
Hi, I'm having a bit of a difficulty replicating this error. Investing a bit of time in updating punchclock this weekend, will see if I can figure out what's up.

**Comment by AshleyWright** [comment]
Since restarting atom I also am unable to reproduce.

**Comment by schelmo** [comment]
Hi, I have this problem too
if i change the order of
```
moment ?= require "moment"
twix ?= require "twix"
```
to:
```
twix ?= require "twix"
moment ?= require "moment"
```
in https://github.com/queenp/punchclock/blob/master/lib/timer.coffee#L410

everything works. but i have no idea why ;)
