### ISSUE TITLE
Uncaught TypeError: this.clockView.addClass is not a function

### ISSUE THREAD

**Issue by abelncm** [queenp/punchclock#15]
[Enter steps to reproduce below:]

1. Just pausing it

**Atom Version**: 1.2.0
**System**: Microsoft Windows 7 Home Premium 
**Thrown From**: [punchclock](https://github.com/queenp/punchclock) package, v0.6.5

### Stack Trace

Uncaught TypeError: this.clockView.addClass is not a function

```
At /C:/Users/x/.atom/packages/punchclock/lib/timer.coffee:152

TypeError: this.clockView.addClass is not a function
    at Timer.module.exports.Timer.pause (file:///C:/Users/x/.atom/packages/punchclock/lib/timer.coffee:168:28)
    at atom-workspace.<anonymous> (file:///C:/Users/x/.atom/packages/punchclock/lib/punchclock.coffee:51:75)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (C:\Users\x\AppData\Local\atom\app-1.2.0\resources\app.asar\src\command-registry.js:260:29)
    at C:\Users\x\AppData\Local\atom\app-1.2.0\resources\app.asar\src\command-registry.js:3:61
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (C:\Users\x\AppData\Local\atom\app-1.2.0\resources\app.asar\node_modules\atom-keymap\lib\keymap-manager.js:533:16)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (C:\Users\x\AppData\Local\atom\app-1.2.0\resources\app.asar\node_modules\atom-keymap\lib\keymap-manager.js:356:22)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeydown (C:\Users\x\AppData\Local\atom\app-1.2.0\resources\app.asar\src\window-event-handler.js:99:36)
    at HTMLDocument.<anonymous> (C:\Users\Abel\AppData\Local\atom\app-1.2.0\resources\app.asar\src\window-event-handler.js:3:61)
```

### Commands

```
     -0:17.8.0 punchclock:start (atom-text-editor.editor.is-focused)
     -0:15.3.0 punchclock:pause (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "packagesWithKeymapsDisabled": [
      "ask-stack",
      "atom-terminal",
      "php-cs-fixer",
      "Remote-FTP",
      "imdone-atom",
      "punchclock"
    ]
  }
}
```

### Installed Packages

```coffee
# User
color-picker, v2.0.13
file-icons, v1.6.11
git-log, v0.4.1
imdone-atom, v1.1.59
jquery-snippets, v11.0.0
linter, v1.11.1
linter-csslint, v1.1.0
linter-htmlhint, v0.2.1
linter-jshint, vundefined
minimap, v4.16.0
php-twig, v4.0.0
pigments, v0.18.1
punchclock, v0.6.5
Remote-FTP, v0.7.10
symbols-tree-view, v0.10.1
tree-view-git-status, v0.2.2
wakatime, v5.0.0

# Dev
No dev packages
```

**Comment by ZedStack** [comment]
Having the same problem in Atom 1.2.3

**Comment by yriveiro** [comment]
Having the issue in Atom 1.3.2.

The clock pauses.

**Comment by zeiv** [comment]
Also gives the opposite error on unpause, `this.clockView.removeClass` is not defined.

**Comment by queenp** [comment]
Hi, really sorry about this, I wrote elsewhere I think on this repo -- I don't have the time to maintain it in the long run. I'd be more than happy to help merge any PRs people have, but I'm short on opportunities to fix things heading into the future, and atom's underlying API (at least last I checked) is moving faster than I can keep up with.

Apologies.

P
