### ISSUE TITLE
Uncaught Error: ENOENT: no such file or directory, scandir '/Users/yriveiro/.atom/.punchclock'

### ISSUE THREAD

**Issue by yriveiro** [queenp/punchclock#18]
[Enter steps to reproduce below:]

1. Try to open dashboard

**Atom Version**: 1.3.2
**System**: Mac OS X 10.10.5
**Thrown From**: [punchclock](https://github.com/queenp/punchclock) package, v0.6.5

### Stack Trace

Uncaught Error: ENOENT: no such file or directory, scandir '/Users/yriveiro/.atom/.punchclock'

```
At fs.js:813

Error: ENOENT: no such file or directory, scandir '/Users/yriveiro/.atom/.punchclock'
    at Error (native)
    at Object.fs.readdirSync (fs.js:813:18)
    at Object.fs.readdirSync (ATOM_SHELL_ASAR.js:454:28)
    at Reporter.module.exports.Reporter.getProjects (/Users/yriveiro/.atom/packages/punchclock/lib/reporter.coffee:30:33)
    at DashboardView.render (/Users/yriveiro/.atom/packages/punchclock/lib/views/dashboard.js:26:91)
    at Object.createElement (/Users/yriveiro/.atom/packages/punchclock/node_modules/etch/dist/create-element.js:20:40)
    at new DashboardView (/Users/yriveiro/.atom/packages/punchclock/lib/views/dashboard.js:19:14)
    at DashboardView.init (/Users/yriveiro/.atom/packages/punchclock/node_modules/etch/dist/dom.js:55:24)
    at createElement (/Users/yriveiro/.atom/packages/punchclock/node_modules/etch/node_modules/virtual-dom/vdom/create-element.js:19:22)
    at createElement (/Users/yriveiro/.atom/packages/punchclock/node_modules/etch/node_modules/virtual-dom/vdom/create-element.js:39:25)
    at createElement (/Users/yriveiro/.atom/packages/punchclock/node_modules/etch/node_modules/virtual-dom/vdom/create-element.js:39:25)
    at createElement (/Users/yriveiro/.atom/packages/punchclock/node_modules/etch/node_modules/virtual-dom/vdom/create-element.js:39:25)
    at Object.createElement (/Users/yriveiro/.atom/packages/punchclock/node_modules/etch/dist/create-element.js:22:64)
    at new PunchclockView (/Users/yriveiro/.atom/packages/punchclock/lib/views/index.js:36:14)
    at createPunchclockView (/Users/yriveiro/.atom/packages/punchclock/lib/punchclock.coffee:15:16)
    at /Users/yriveiro/.atom/packages/punchclock/lib/punchclock.coffee:109:35
    at Workspace.module.exports.Workspace.openURIInPane (/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app.asar/src/workspace.js:454:22)
    at Workspace.module.exports.Workspace.open (/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app.asar/src/workspace.js:393:19)
    at Object.module.exports.dashboard (/Users/yriveiro/.atom/packages/punchclock/lib/punchclock.coffee:163:24)
    at atom-workspace.<anonymous> (/Users/yriveiro/.atom/packages/punchclock/lib/punchclock.coffee:57:73)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app.asar/src/command-registry.js:260:29)
    at /opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61
    at CommandPaletteView.module.exports.CommandPaletteView.confirmed (/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app.asar/node_modules/command-palette/lib/command-palette-view.js:183:32)
    at CommandPaletteView.module.exports.SelectListView.confirmSelection (/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app.asar/node_modules/atom-space-pen-views/lib/select-list-view.js:338:21)
    at space-pen-div.atom.commands.add.core:confirm (/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app.asar/node_modules/atom-space-pen-views/lib/select-list-view.js:109:19)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app.asar/src/command-registry.js:260:29)
    at /opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:536:16)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:359:22)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeydown (/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:97:36)
    at HTMLDocument.<anonymous> (/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:3:61)
```

### Commands

```
  2x -3:10.8.0 tree-view:reveal-active-file (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-seti-syntax.theme-atom-dark-ui)
     -1:40.2.0 core:save (atom-text-editor.editor.vim-mode.insert-mode.is-focused)
  8x -1:38.6.0 tree-view:reveal-active-file (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-seti-syntax.theme-atom-dark-ui)
     -0:49.7.0 docblockr:parse-enter (atom-text-editor.editor.vim-mode.insert-mode.is-focused)
     -0:49.7.0 editor:newline (atom-text-editor.editor.vim-mode.insert-mode.is-focused)
     -0:40.4.0 core:move-right (atom-text-editor.editor.vim-mode.insert-mode.is-focused)
     -0:39.5.0 core:save (atom-text-editor.editor.vim-mode.insert-mode.is-focused)
     -0:31.5.0 command-palette:toggle (atom-text-editor.editor.vim-mode.insert-mode.is-focused)
     -0:30 core:backspace (atom-text-editor.editor.mini.is-focused)
     -0:28.3.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:28.3.0 punchclock:start (atom-text-editor.editor.vim-mode.insert-mode)
     -0:09.6.0 command-palette:toggle (atom-text-editor.editor.vim-mode.insert-mode.is-focused)
  5x -0:04.7.0 core:move-down (atom-text-editor.editor.mini.is-focused)
     -0:03.7.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:03.7.0 punchclock:dashboard (atom-text-editor.editor.vim-mode.insert-mode)
     -0:03.7.0 tree-view:reveal-active-file (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-seti-syntax.theme-atom-dark-ui)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "autocomplete",
      "git-tab-status",
      "hyperclick",
      "wrap-guide",
      "autocomplete-php",
      "relative-numbers"
    ],
    "themes": [
      "atom-dark-ui",
      "seti-syntax"
    ],
    "projectHome": "/Users/yriveiro/Development/github/"
  },
  "punchclock": {
    "autoEnableTimeTrackingOnLoad": true
  }
}
```

### Installed Packages

```coffee
# User
atom-autocomplete-php, v0.18.4
atom-beautify, v0.28.19
atom-cli-diff, v1.1.0
atom-html-preview, v0.1.13
atom-jade, v0.3.0
atom-pair, v2.0.10
autocomplete-paths, v1.0.2
autocomplete-phpunit, v1.0.2
color-picker, v2.0.14
color-tabs, v0.1.8
docblockr, v0.7.3
file-icons, v1.6.13
git-diff-details, v0.21.0
go-plus, v3.5.2
highlight-line, v0.11.0
inline-messenger, v1.2.8
language-rust, v0.4.5
linter, v1.11.3
linter-jsonlint, v1.1.4
linter-php, v1.1.6
linter-rust, v0.3.0
linter-shellcheck, v1.1.0
local-history, v3.2.3
minimap, v4.19.0
minimap-bookmarks, v0.2.0
minimap-git-diff, v4.1.8
multi-wrap-guide, v0.23.4
php-cs-fixer, v2.5.1
phpunit, v1.2.0
phpunit-snippets, v0.1.0
pigments, v0.19.5
pretty-json, v0.4.1
project-manager, v2.6.5
punchclock, v0.6.5
rust-api-docs-helper, v0.5.1
seti-syntax, v0.4.1
synced-sidebar, v0.4.3
travis-ci-status, v0.18.0
vim-mode, v0.64.0
wakatime, v5.0.2

# Dev
No dev packages
```

**Comment by Marsovski** [comment]
+1
