### ISSUE TITLE
Uncaught Error: ENOENT: no such file or directory, scandir 'C:\Users\SAKIB\.atom\.timekeeper'

### ISSUE THREAD

**Issue by rsakib15** [queenp/punchclock#3]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.0.0
**System**: Microsoft Windows 8.1
**Thrown From**: [punchclock](https://github.com/queenp/punchclock) package, v0.5.0

### Stack Trace

Uncaught Error: ENOENT: no such file or directory, scandir 'C:\Users\SAKIB\.atom\.timekeeper'

```
At fs.js:805

Error: ENOENT: no such file or directory, scandir 'C:\Users\SAKIB\.atom\.timekeeper'
    at Error (native)
    at Object.fs.readdirSync (fs.js:805:18)
    at Object.fs.readdirSync (ATOM_SHELL_ASAR.js:441:28)
    at Reporter.module.exports.Reporter.getProjects (C:\Users\SAKIB\.atom\packages\punchclock\lib\reporter.coffee:44:27)
    at DashboardView.module.exports.DashboardView.initialize (C:\Users\SAKIB\.atom\packages\punchclock\lib\views\dashboard.coffee:54:39)
    at DashboardView.View (C:\Users\SAKIB\AppData\Local\atom\app-1.0.0\resources\app.asar\node_modules\atom-space-pen-views\node_modules\space-pen\lib\space-pen.js:184:25)
    at new DashboardView (C:\Users\SAKIB\.atom\packages\punchclock\lib\views\dashboard.coffee:46:43)
    at TimekeeperView.module.exports.TimekeeperView.initialize (C:\Users\SAKIB\.atom\packages\punchclock\lib\views\index.coffee:71:29)
    at TimekeeperView.View (C:\Users\SAKIB\AppData\Local\atom\app-1.0.0\resources\app.asar\node_modules\atom-space-pen-views\node_modules\space-pen\lib\space-pen.js:184:25)
    at TimekeeperView.ScrollView (C:\Users\SAKIB\AppData\Local\atom\app-1.0.0\resources\app.asar\node_modules\atom-space-pen-views\lib\scroll-view.js:12:47)
```

### Commands

```
     -9:54.8.0 core:select-all (atom-text-editor.editor.mini.is-focused)
     -9:54.1.0 core:paste (atom-text-editor.editor.mini.is-focused)
     -9:52.8.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -4:51 core:paste (atom-text-editor.editor.mini.is-focused)
     -4:49.4.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -1:02.0 timekeeper:start (div.settings-view.pane-item)
  2x -0:44.4.0 timekeeper:dashboard (div.settings-view.pane-item)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "html-include-resource"
    ]
  }
}
```

### Installed Packages

```coffee
# User
color-picker, v2.0.7
emmet, v2.3.10
file-icons, v1.5.8
javascript-snippets, v1.0.0
punchclock, v0.5.0
run-in-browser, v0.1.3
time-status, v1.1.0
w3c-validation, v0.2.0

# Dev
No dev packages
```

**Comment by Vesuvium** [comment]
Happened to me as well, on Debian 8.
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.0.0
**System**: Debian GNU/Linux
**Thrown From**: [punchclock](https://github.com/queenp/punchclock) package, v0.5.0


### Stack Trace

Uncaught Error: ENOENT: no such file or directory, scandir '/home/jacopo/.atom/.timekeeper'

```
At fs.js:805

Error: ENOENT: no such file or directory, scandir '/home/jacopo/.atom/.timekeeper'
    at Error (native)
    at Object.fs.readdirSync (fs.js:805:18)
    at Object.fs.readdirSync (ATOM_SHELL_ASAR.js:441:28)
    at Reporter.module.exports.Reporter.getProjects (/home/jacopo/.atom/packages/punchclock/lib/reporter.coffee:44:27)
    at DashboardView.module.exports.DashboardView.initialize (/home/jacopo/.atom/packages/punchclock/lib/views/dashboard.coffee:54:39)
    at DashboardView.View (/usr/share/atom/resources/app.asar/node_modules/atom-space-pen-views/node_modules/space-pen/lib/space-pen.js:184:25)
    at new DashboardView (/home/jacopo/.atom/packages/punchclock/lib/views/dashboard.coffee:46:43)
    at TimekeeperView.module.exports.TimekeeperView.initialize (/home/jacopo/.atom/packages/punchclock/lib/views/index.coffee:71:29)
    at TimekeeperView.View (/usr/share/atom/resources/app.asar/node_modules/atom-space-pen-views/node_modules/space-pen/lib/space-pen.js:184:25)
    at TimekeeperView.ScrollView (/usr/share/atom/resources/app.asar/node_modules/atom-space-pen-views/lib/scroll-view.js:12:47)
```

### Commands

```
     -9:20.3.0 settings-view:check-for-package-updates (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui)
 12x -7:38.6.0 core:backspace (atom-text-editor.editor.mini.is-focused)
  2x -4:44 core:confirm (atom-text-editor.editor.mini.is-focused)
     -2:15.7.0 line-count:open (atom-text-editor.editor.is-focused)
  2x -1:00.9.0 timekeeper:start (atom-text-editor.editor.is-focused)
     -0:51.6.0 deprecation-cop:view (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui)
     -0:33.5.0 timekeeper:pause (atom-text-editor.editor.is-focused)
     -0:23.2.0 timekeeper:reset (div.settings-view.pane-item)
     -0:09.9.0 timekeeper:abort (div.settings-view.pane-item)
     -0:01.9.0 timekeeper:dashboard (div.settings-view.pane-item)
```

### Config

```json
{
  "core": {}
}
```

### Installed Packages

```coffee
# User
line-count, v0.3.5
pigments, v0.8.1
punchclock, v0.5.0

# Dev
No dev packages
```

**Comment by queenp** [comment]
Hi, this should be fixed now hopefully.
